import { Octokit } from '@octokit/rest';
import { GitHubAuthError, RepoNotFoundError } from './errors.js';

function parseRemoteUrl(url) {
  // Handle SSH: git@github.example.com:owner/repo.git (any hostname containing "github")
  let match = url.match(/[a-z0-9.-]*github[a-z0-9.-]*[:/](.+?)\/(.+?)(?:\.git)?$/);
  if (match) return { owner: match[1], repo: match[2] };
  // Handle HTTPS: https://github.example.com/owner/repo.git (any hostname containing "github")
  match = url.match(/[a-z0-9.-]*github[a-z0-9.-]*\/(.+?)\/(.+?)(?:\.git)?$/);
  if (match) return { owner: match[1], repo: match[2] };
  return null;
}

export async function createPR(config, { title, body, branch, base, draft = true, labels = ['adamant-wish'], remoteUrl }) {
  const parsed = parseRemoteUrl(remoteUrl);
  if (!parsed) throw new RepoNotFoundError(remoteUrl);

  const octokit = new Octokit({ auth: config.github_token });

  try {
    const { data } = await octokit.pulls.create({
      owner: parsed.owner,
      repo: parsed.repo,
      title,
      body: body + '\n\n---\nGenerated by Adamant CLI',
      head: branch,
      base: base || 'main',
      draft,
    });

    // Try to add labels (non-blocking)
    try {
      await octokit.issues.addLabels({
        owner: parsed.owner,
        repo: parsed.repo,
        issue_number: data.number,
        labels,
      });
    } catch { /* labels may not exist yet */ }

    return { url: data.html_url, number: data.number };
  } catch (err) {
    if (err.status === 401 || err.status === 403) throw new GitHubAuthError();
    if (err.status === 404) throw new RepoNotFoundError(`${parsed.owner}/${parsed.repo}`);
    throw err;
  }
}

export async function getDefaultBranch(config, remoteUrl) {
  const parsed = parseRemoteUrl(remoteUrl);
  if (!parsed) return 'main';

  const octokit = new Octokit({ auth: config.github_token });
  try {
    const { data } = await octokit.repos.get({ owner: parsed.owner, repo: parsed.repo });
    return data.default_branch;
  } catch {
    return 'main';
  }
}
